version: '3.1'

services:

  db:
    image: postgres:12-alpine
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: user
      POSTGRES_DB: app
    ports:
      - '5432:5432'